# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "成都犀牛"

# A description of your site for meta tag, search engine results.
description: "会当水击三千里，自信人生二百年"

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://scriptor-jekyll.netlify.com"

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: Personal
    url: /personal/
  - text: Articles  
    url: /articles/
  - text: comcloud
    url: https://github.com/comcloud

# Collections for blog series
collections:
  blog_series:
    output: true
    permalink: /blog/:path/
  llm_articles:
    output: true
    permalink: /blog/LLM/:name/
  deepseek_articles:
    output: true
    permalink: /blog/LLM/deepseek/:name/
  qwen_articles:
    output: true
    permalink: /blog/LLM/qwen/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: blog_series
    values:
      layout: page
  - scope:
      path: ""
      type: llm_articles
    values:
      layout: markdown
  - scope:
      path: ""
      type: deepseek_articles
    values:
      layout: markdown
  - scope:
      path: ""
      type: qwen_articles
    values:
      layout: markdown
  - scope:
      path: "blog/**/*.md"
    values:
      layout: markdown
      permalink: /blog/:path/
  - scope:
      path: "personal/**/*.md"
    values:
      layout: markdown
      permalink: /personal/:path/

# The shortname for your Disqus site to enable comments.
disqus: justgoodthemes

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  content: "&copy; Scriptor all rights reserved. Theme by [JustGoodThemes](https://www.justgoodthemes.com)."
  has_social: true

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: true

# Include markdown files in processing
include: ["blog/**/*.md", "personal/**/*.md"]

# Enable processing of all markdown files
keep_files: [".git", ".svn"]

# Exclude unnecessary files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata